[server]
headless = true
enableCORS = false
enableXsrfProtection = false
baseUrlPath = ""
enableStaticServing = true
allowRunOnSave = false

[global]
developmentMode = false

[client]
caching = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
